spring:
  application:
    name: config-server
  cloud:
    inetutils:
      timeout-seconds: 5000
    config:
      server:
        git:
          uri: https://github.com/NextFeng/cloud_config.git
          username: 1225842878@qq.com
          password: Http1024
          basedir: D:/lcdz/cloud
          force-pull: true
  rabbitmq:
    host: 192.168.0.101
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://lcdz:lcdzsoft@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh
logging:
  level:
    org.springframework.cloud.bus: debug