eureka:
  client:
    service-url:
     defaultZone: http://lcdz:lcdzsoft@localhost:8761/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
spring:
  application:
    name: eureka
  security:
    user:
      name: lcdz
      password: lcdzsoft
      roles: SUPERUSER
server:
  port: 8761

