eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: true
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
spring:
  application:
    name: eureka
server:
  port: 8761

