eureka:
  client:
    service-url:
      defaultZone: http://lcdz:lcdzsoft@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
spring:
  application:
    name: product-server
server:
  port: 8080
feign:
  hystrix:
    enabled:
management:
  server:
    servlet:
      context-path: /
#fegin下面的超时时间需要 ribbon 和 hystrix 同时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000    # ribbon read超时时间
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 0 #对切换实例的重试次数，默认1