eureka:
  client:
    service-url:
      defaultZone: http://lcdz:lcdzsoft@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.0.105
spring:
  application:
    name: product-server
server:
  port: 8080
feign:
  hystrix:
    enabled: true